// Generated by LiveScript 1.3.1
(function(){
  var yamlfile, fs, path, cached_secrets, getsecret_init, getsecret;
  yamlfile = require('yamlfile');
  fs = require('fs');
  path = require('path');
  cached_secrets = null;
  getsecret_init = function(){
    var homepath, home_secrets, k, ref$, v, results$ = [];
    cached_secrets = {};
    homepath = process.env.HOME;
    if (homepath == null) {
      homepath = process.env.USERPROFILE;
    }
    if (homepath != null) {
      home_secrets = path.join(homepath, '.getsecret.yaml');
      if (fs.existsSync(home_secrets)) {
        for (k in ref$ = yamlfile.readFileSync(home_secrets)) {
          v = ref$[k];
          cached_secrets[k] = v;
        }
      }
    }
    if (fs.existsSync('.getsecret.yaml')) {
      for (k in ref$ = yamlfile.readFileSync('.getsecret.yaml')) {
        v = ref$[k];
        cached_secrets[k] = v;
      }
    }
    for (k in ref$ = process.env) {
      v = ref$[k];
      results$.push(cached_secrets[k] = v);
    }
    return results$;
  };
  getsecret = function(name){
    if (cached_secrets == null) {
      getsecret_init();
    }
    return cached_secrets[name];
  };
  module.exports = getsecret;
}).call(this);
